version: "2"

run:
  tests: false
  timeout: 5m

linters:
  default: fast
  disable:
    - cyclop
    - depguard
    - funlen
    - gochecknoinits
    - lll
    - mnd
    - nlreturn
    - wsl
    - wsl_v5
