package workflow

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/metalagman/omnidist/internal/config"
)

const (
	DefaultCIWorkflowPath = ".github/workflows/omnidist-release.yml"
	defaultNPXPackage     = "@omnidist/omnidist"
	defaultNPXVersion     = "latest"
)

var (
	npmPackageNamePattern = regexp.MustCompile(`^(?:@[a-z0-9][a-z0-9._-]*/)?[a-z0-9][a-z0-9._-]*$`)
	// Supports common npm dist-tags and semver/range syntax while rejecting shell control chars.
	npmVersionSpecPattern = regexp.MustCompile(`^[A-Za-z0-9.*xXvV_+~^<>=| -]+$`)
)

type CIWorkflowOptions struct {
	NPXPackage string
	NPXVersion string
}

func GenerateGitHubReleaseWorkflow(cfg *config.Config, opts CIWorkflowOptions) (string, error) {
	if cfg == nil {
		return "", fmt.Errorf("config is nil")
	}

	packageName := strings.TrimSpace(opts.NPXPackage)
	if packageName == "" {
		packageName = defaultNPXPackage
	}

	version := strings.TrimSpace(opts.NPXVersion)
	if version == "" {
		version = defaultNPXVersion
	}

	installCmd, err := buildNPXInstallCommand(packageName, version)
	if err != nil {
		return "", err
	}

	content := fmt.Sprintf(`# Generated by "omnidist ci". Re-run the command to refresh this workflow.
name: omnidist-release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      UV_PUBLISH_TOKEN: ${{ secrets.UV_PUBLISH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - uses: actions/setup-node@v4
      - uses: astral-sh/setup-uv@v6
      - name: Install omnidist
        run: %q
      - name: Build artifacts
        run: omnidist build
      - name: Stage artifacts
        run: omnidist stage
      - name: Verify artifacts
        run: omnidist verify
      - name: Publish artifacts
        run: omnidist publish
`, installCmd)

	return content, nil
}

func WriteGitHubReleaseWorkflow(path string, content string, force bool) error {
	workflowPath := strings.TrimSpace(path)
	if workflowPath == "" {
		return fmt.Errorf("workflow path is empty")
	}
	if strings.TrimSpace(content) == "" {
		return fmt.Errorf("workflow content is empty")
	}

	if !force {
		if _, err := os.Stat(workflowPath); err == nil {
			return fmt.Errorf("workflow file %s already exists; rerun with --force to overwrite", workflowPath)
		} else if !os.IsNotExist(err) {
			return fmt.Errorf("stat workflow file %s: %w", workflowPath, err)
		}
	}

	if err := os.MkdirAll(filepath.Dir(workflowPath), 0755); err != nil {
		return fmt.Errorf("create workflow directory: %w", err)
	}

	if err := os.WriteFile(workflowPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("write workflow file %s: %w", workflowPath, err)
	}

	return nil
}

func buildNPXInstallCommand(packageName string, version string) (string, error) {
	if !npmPackageNamePattern.MatchString(packageName) {
		return "", fmt.Errorf("invalid npx package name %q", packageName)
	}
	if !npmVersionSpecPattern.MatchString(version) {
		return "", fmt.Errorf("invalid npx version spec %q", version)
	}

	packageSpec := fmt.Sprintf("%s@%s", packageName, version)
	return fmt.Sprintf("npm install -g %s", shellQuote(packageSpec)), nil
}

func shellQuote(s string) string {
	if s == "" {
		return "''"
	}
	return "'" + strings.ReplaceAll(s, "'", `'"'"'`) + "'"
}
