package workflow

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/metalagman/omnidist/internal/config"
)

const (
	// DefaultCIWorkflowPath is the default output path for the generated GitHub Actions workflow.
	DefaultCIWorkflowPath = ".github/workflows/omnidist-release.yml"
	defaultNPXPackage     = "@omnidist/omnidist"
	defaultNPXVersion     = "latest"
	trustedNodeVersion    = "24"
	npmRegistryURL        = "https://registry.npmjs.org"
	rubygemsRegistryURL   = "https://rubygems.org"
)

var (
	npmPackageNamePattern = regexp.MustCompile(`^(?:@[a-z0-9][a-z0-9._-]*/)?[a-z0-9][a-z0-9._-]*$`)
	// Supports common npm dist-tags and semver/range syntax while rejecting shell control chars.
	npmVersionSpecPattern = regexp.MustCompile(`^[A-Za-z0-9.*xXvV_+~^<>=| -]+$`)
)

// CIWorkflowOptions customizes the generated GitHub release workflow.
type CIWorkflowOptions struct {
	NPXPackage string
	NPXVersion string
}

// GenerateGitHubReleaseWorkflow renders a GitHub Actions workflow for omnidist releases.
func GenerateGitHubReleaseWorkflow(cfg *config.Config, opts CIWorkflowOptions) (string, error) {
	if cfg == nil {
		return "", fmt.Errorf("config is nil")
	}

	packageName := strings.TrimSpace(opts.NPXPackage)
	if packageName == "" {
		packageName = defaultNPXPackage
	}

	version := strings.TrimSpace(opts.NPXVersion)
	if version == "" {
		version = defaultNPXVersion
	}

	useLocalSource := useLocalOmnidistSource(cfg, packageName)
	installCmd := ""
	if !useLocalSource {
		var err error
		installCmd, err = buildNPXInstallCommand(packageName, version)
		if err != nil {
			return "", err
		}
	}
	enabledNames, err := cfg.EnabledDistributionNames()
	if err != nil {
		return "", fmt.Errorf("resolve enabled distributions: %w", err)
	}
	enabled := make(map[string]bool, len(enabledNames))
	for _, name := range enabledNames {
		enabled[name] = true
	}
	only := shellQuote(strings.Join(enabledNames, ","))
	workspaceDir := cfg.EffectiveWorkspaceDir()
	workspaceDistDir := workspaceDir + "/dist"
	omnidistCmd := workflowOmnidistCommand(cfg, useLocalSource)

	var content strings.Builder
	content.WriteString(`# Generated by "omnidist ci". Re-run the command to refresh this workflow.
name: omnidist-release
on:
  push:
    tags:
      - "v*"
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
jobs:
`)
	content.WriteString(renderPrepareJob(installCmd, omnidistCmd, only, workspaceDir, workspaceDistDir, enabled, useLocalSource))
	if enabled["npm"] {
		content.WriteString(renderNPMPublishJob(cfg, installCmd, omnidistCmd, useLocalSource))
	}
	if enabled["uv"] {
		content.WriteString(renderUVPublishJob(installCmd, omnidistCmd, useLocalSource))
	}
	if enabled["gem"] {
		content.WriteString(renderGemPublishJob(cfg, installCmd, omnidistCmd, useLocalSource))
	}
	content.WriteString(renderReleaseJob(workspaceDistDir))

	return content.String(), nil
}

func renderPrepareJob(installCmd, omnidistCmd, only, workspaceDir, workspaceDistDir string, enabled map[string]bool, useLocalSource bool) string {
	nodeSetup := ""
	if !useLocalSource {
		nodeSetup = githubActionsNodeSetupStep()
	}
	uvSetup := ""
	if enabled["uv"] {
		uvSetup = "      - uses: astral-sh/setup-uv@v6"
	}
	rubySetup := ""
	if enabled["gem"] {
		rubySetup = workflowRubySetupStep()
	}
	return fmt.Sprintf(`  prepare:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
%s
%s
%s
%s
      - name: Build artifacts
        run: %s build
      - name: Stage artifacts
        run: %s stage --only %s
      - name: Verify artifacts
        run: %s verify --only %s
      - name: Pack staged artifacts
        run: tar -czf omnidist-staged.tgz %s
      - name: Upload staged artifacts
        uses: actions/upload-artifact@v4
        with:
          name: omnidist-staged
          path: omnidist-staged.tgz
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: %s/**/*
          if-no-files-found: error

`, nodeSetup, uvSetup, rubySetup, workflowInstallStep(installCmd), omnidistCmd, omnidistCmd, only, omnidistCmd, only, workspaceDir, workspaceDistDir)
}

func renderNPMPublishJob(cfg *config.Config, installCmd, omnidistCmd string, useLocalSource bool) string {
	return fmt.Sprintf(`  publish_npm:
    needs: prepare
    runs-on: ubuntu-latest
    permissions:
      contents: read
%s
%s
    steps:
      - uses: actions/checkout@v4
%s
%s
%s
      - name: Download staged artifacts
        uses: actions/download-artifact@v4
        with:
          name: omnidist-staged
      - name: Restore staged artifacts
        run: tar -xzf omnidist-staged.tgz
      - name: Publish npm artifacts
        run: %s npm publish

`, workflowPublishNPMPermissions(cfg), workflowPublishNPMEnv(cfg), workflowGoSetupStep(useLocalSource), githubActionsNodeSetupStep(), workflowInstallStep(installCmd), omnidistCmd)
}

func renderUVPublishJob(installCmd, omnidistCmd string, useLocalSource bool) string {
	nodeSetup := ""
	if !useLocalSource {
		nodeSetup = githubActionsNodeSetupStep()
	}
	return fmt.Sprintf(`  publish_uv:
    needs: prepare
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      UV_PUBLISH_TOKEN: ${{ secrets.UV_PUBLISH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
%s
%s
%s
      - uses: astral-sh/setup-uv@v6
      - name: Download staged artifacts
        uses: actions/download-artifact@v4
        with:
          name: omnidist-staged
      - name: Restore staged artifacts
        run: tar -xzf omnidist-staged.tgz
      - name: Publish uv artifacts
        run: %s uv publish

`, workflowGoSetupStep(useLocalSource), nodeSetup, workflowInstallStep(installCmd), omnidistCmd)
}

func renderGemPublishJob(cfg *config.Config, installCmd, omnidistCmd string, useLocalSource bool) string {
	nodeSetup := ""
	if !useLocalSource {
		nodeSetup = githubActionsNodeSetupStep()
	}
	return fmt.Sprintf(`  publish_gem:
    needs: prepare
    runs-on: ubuntu-latest
    permissions:
      contents: read
%s
%s
    steps:
      - uses: actions/checkout@v4
%s
%s
%s
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
%s
      - name: Download staged artifacts
        uses: actions/download-artifact@v4
        with:
          name: omnidist-staged
      - name: Restore staged artifacts
        run: tar -xzf omnidist-staged.tgz
      - name: Publish gem artifacts
        run: %s gem publish

`, workflowPublishGemPermissions(cfg), workflowPublishGemEnvBlock(cfg), workflowGoSetupStep(useLocalSource), nodeSetup, workflowInstallStep(installCmd), workflowPublishGemCredentialStep(cfg), omnidistCmd)
}

func renderReleaseJob(workspaceDistDir string) string {
	return fmt.Sprintf(`  release:
    needs: prepare
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: %s
          merge-multiple: true
      - name: Prepare release assets
        run: |
          mkdir -p release-assets
          while IFS= read -r -d '' f; do
            rel="${f#%s/}"
            os="${rel%%%%/*}"
            rem="${rel#*/}"
            arch="${rem%%%%/*}"
            name="${rel##*/}"
            ext=""
            base="$name"
            if [[ "$name" == *.exe ]]; then
              ext=".exe"
              base="${name%%.exe}"
            fi
            cp "$f" "release-assets/${base}-${os}-${arch}${ext}"
          done < <(find %s -type f ! -name VERSION -print0 | sort -z)
      - name: Generate checksums
        run: |
          cd release-assets
          sha256sum * > checksums.txt
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release-assets/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
`, workspaceDistDir, workspaceDistDir, workspaceDistDir)
}

// WriteGitHubReleaseWorkflow writes generated workflow content to disk.
func WriteGitHubReleaseWorkflow(path string, content string, force bool) error {
	workflowPath := strings.TrimSpace(path)
	if workflowPath == "" {
		return fmt.Errorf("workflow path is empty")
	}
	if strings.TrimSpace(content) == "" {
		return fmt.Errorf("workflow content is empty")
	}

	if !force {
		if _, err := os.Stat(workflowPath); err == nil {
			return fmt.Errorf("workflow file %s already exists; rerun with --force to overwrite", workflowPath)
		} else if !os.IsNotExist(err) {
			return fmt.Errorf("stat workflow file %s: %w", workflowPath, err)
		}
	}

	if err := os.MkdirAll(filepath.Dir(workflowPath), 0755); err != nil {
		return fmt.Errorf("create workflow directory: %w", err)
	}

	if err := os.WriteFile(workflowPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("write workflow file %s: %w", workflowPath, err)
	}

	return nil
}

func buildNPXInstallCommand(packageName string, version string) (string, error) {
	if !npmPackageNamePattern.MatchString(packageName) {
		return "", fmt.Errorf("invalid npx package name %q", packageName)
	}
	if !npmVersionSpecPattern.MatchString(version) {
		return "", fmt.Errorf("invalid npx version spec %q", version)
	}

	packageSpec := fmt.Sprintf("%s@%s", packageName, version)
	return fmt.Sprintf("npm install -g %s", shellQuote(packageSpec)), nil
}

func workflowOmnidistCommand(cfg *config.Config, useLocalSource bool) string {
	base := "omnidist"
	if useLocalSource {
		base = "go run ./cmd/omnidist"
	}
	if cfg.IsProfilesMode() {
		return fmt.Sprintf("%s --profile %s", base, shellQuote(cfg.SelectedProfile()))
	}
	return base
}

func useLocalOmnidistSource(cfg *config.Config, packageName string) bool {
	if cfg == nil {
		return false
	}
	return packageName == defaultNPXPackage &&
		strings.TrimSpace(cfg.Tool.Name) == "omnidist" &&
		strings.TrimSpace(cfg.Tool.Main) == "./cmd/omnidist"
}

func githubActionsNodeSetupStep() string {
	return fmt.Sprintf(`      - uses: actions/setup-node@v6
        with:
          node-version: %s
          registry-url: %s
          package-manager-cache: false`, shellQuote(trustedNodeVersion), shellQuote(npmRegistryURL))
}

func workflowGoSetupStep(enabled bool) string {
	if !enabled {
		return ""
	}
	return `      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"`
}

func workflowInstallStep(command string) string {
	command = strings.TrimSpace(command)
	if command == "" {
		return ""
	}
	return fmt.Sprintf("      - name: Install omnidist\n        run: %s", command)
}

func workflowRubySetupStep() string {
	return `      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'`
}

func workflowPublishNPMPermissions(cfg *config.Config) string {
	if !usesTrustedNPMPublishAuth(cfg) {
		return ""
	}
	return "      id-token: write"
}

func workflowPublishNPMEnv(cfg *config.Config) string {
	if usesTrustedNPMPublishAuth(cfg) {
		return ""
	}
	return `    env:
      NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}`
}

func workflowPublishGemEnvBlock(cfg *config.Config) string {
	if usesTrustedGemPublishAuth(cfg) {
		return ""
	}
	return `    env:
      GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
      GEM_HOST_OTP_CODE: ${{ secrets.RUBYGEMS_OTP_CODE }}`
}

func workflowPublishGemPermissions(cfg *config.Config) string {
	if !usesTrustedGemPublishAuth(cfg) {
		return ""
	}
	return "      id-token: write"
}

func workflowPublishGemCredentialStep(cfg *config.Config) string {
	if !usesTrustedGemPublishAuth(cfg) {
		return ""
	}
	return `      - name: Configure RubyGems trusted publishing credentials
        uses: rubygems/configure-rubygems-credentials@v2.1.0`
}

func usesTrustedGemPublishAuth(cfg *config.Config) bool {
	if cfg == nil {
		return false
	}
	gemDist, ok := cfg.Distributions["gem"]
	if !ok {
		return false
	}
	registry := strings.TrimSpace(gemDist.Registry)
	return strings.TrimSpace(gemDist.PublishAuth) == "trusted" &&
		(registry == "" || registry == rubygemsRegistryURL)
}

func usesTrustedNPMPublishAuth(cfg *config.Config) bool {
	if cfg == nil {
		return false
	}
	npmDist, ok := cfg.Distributions["npm"]
	if !ok {
		return false
	}
	return strings.TrimSpace(npmDist.PublishAuth) == "trusted"
}

func shellQuote(s string) string {
	if s == "" {
		return "''"
	}
	return "'" + strings.ReplaceAll(s, "'", `'"'"'`) + "'"
}
