package workflow

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/metalagman/omnidist/internal/config"
)

const (
	DefaultCIWorkflowPath = ".github/workflows/omnidist-release.yml"
	defaultNPXPackage     = "@omnidist/omnidist"
	defaultNPXVersion     = "latest"
)

type CIWorkflowOptions struct {
	NPXPackage string
	NPXVersion string
}

func GenerateGitHubReleaseWorkflow(cfg *config.Config, opts CIWorkflowOptions) (string, error) {
	if cfg == nil {
		return "", fmt.Errorf("config is nil")
	}

	packageName := strings.TrimSpace(opts.NPXPackage)
	if packageName == "" {
		packageName = defaultNPXPackage
	}

	version := strings.TrimSpace(opts.NPXVersion)
	if version == "" {
		version = defaultNPXVersion
	}

	installCmd := fmt.Sprintf("npm install -g %s@%s", packageName, version)

	content := fmt.Sprintf(`# Generated by "omnidist ci". Re-run the command to refresh this workflow.
name: omnidist-release
on:
  push:
    tags:
      - "v*"
jobs:
  prepare:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - uses: actions/setup-node@v4
      - uses: astral-sh/setup-uv@v6
      - name: Install omnidist
        run: %s
      - name: Build artifacts
        run: omnidist build
      - name: Stage artifacts
        run: omnidist stage
      - name: Verify artifacts
        run: omnidist verify
      - name: Pack staged artifacts
        run: tar -czf omnidist-staged.tgz .omnidist
      - name: Upload staged artifacts
        uses: actions/upload-artifact@v4
        with:
          name: omnidist-staged
          path: omnidist-staged.tgz

  publish_npm:
    needs: prepare
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install omnidist
        run: %[1]s
      - name: Download staged artifacts
        uses: actions/download-artifact@v4
        with:
          name: omnidist-staged
      - name: Restore staged artifacts
        run: tar -xzf omnidist-staged.tgz
      - name: Publish npm artifacts
        run: omnidist npm publish

  publish_uv:
    needs: prepare
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      UV_PUBLISH_TOKEN: ${{ secrets.UV_PUBLISH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: astral-sh/setup-uv@v6
      - name: Install omnidist
        run: %[1]s
      - name: Download staged artifacts
        uses: actions/download-artifact@v4
        with:
          name: omnidist-staged
      - name: Restore staged artifacts
        run: tar -xzf omnidist-staged.tgz
      - name: Publish uv artifacts
        run: omnidist uv publish
`, installCmd)

	return content, nil
}

func WriteGitHubReleaseWorkflow(path string, content string, force bool) error {
	workflowPath := strings.TrimSpace(path)
	if workflowPath == "" {
		return fmt.Errorf("workflow path is empty")
	}
	if strings.TrimSpace(content) == "" {
		return fmt.Errorf("workflow content is empty")
	}

	if !force {
		if _, err := os.Stat(workflowPath); err == nil {
			return fmt.Errorf("workflow file %s already exists; rerun with --force to overwrite", workflowPath)
		} else if !os.IsNotExist(err) {
			return fmt.Errorf("stat workflow file %s: %w", workflowPath, err)
		}
	}

	if err := os.MkdirAll(filepath.Dir(workflowPath), 0755); err != nil {
		return fmt.Errorf("create workflow directory: %w", err)
	}

	if err := os.WriteFile(workflowPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("write workflow file %s: %w", workflowPath, err)
	}

	return nil
}
